### ISSUE TITLE
missing providerConfig mapping for machine image

### ISSUE THREAD

**Issue by lotharbach** [gardener/gardener-extension-provider-openstack#1021]
**How to categorize this issue?**

/area usability
/kind bug
/platform openstack

**What happened**:

Cloudprofile validation fails without region<->id mapping for machineImages
`Error from server: error when patching "cloudprofiles/regiocloud.yaml": admission webhook "validator.admission-openstack.extensions.gardener.cloud" denied the request: spec.machineImages[0].versions[0]: Required value: missing providerConfig mapping for machine image version gardenlinux@1592.8.0 and architecture: amd64
`

when cloudprofile contains:

```
   machineImages:
      - name: gardenlinux
        versions:
          - version: 1592.8.0
            image: 'Garden Linux 1592.8'
```

Validation works when cloudprofile is changed to:
```
    machineImages:
      - name: gardenlinux
        versions:
          - version: 1592.8.0
            image: 'Garden Linux 1592.8'
            regions:
              - name: RegionA
                id: whatever
```

**What you expected to happen**:
While it is "strongly discouraged" to not use image IDs, it should still work until it gets removed.

**Environment**:

- Gardener version (if relevant): v1.116.0
- Extension version: v1.47.0
