### ISSUE TITLE
Implement `Worker` controller for OpenStack provider

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extension-provider-openstack#11]
Similar to how we have implemented the `Worker` extension resource controller for the [AWS provider](https://github.com/gardener/gardener-extensions/pull/71) let's please now do it for OpenStack.

There is no special provider config required to be implemented, however, we should have [component configuration](https://github.com/gardener/gardener-extensions/pull/71/files#diff-ec48bd1cd4bb7c2b51603f67ee4bbee3) for the controller that should look as follows:

```yaml
---
apiVersion: openstack.provider.extensions.config.gardener.cloud/v1alpha1
kind: ControllerConfiguration
machineImages:
- name: coreos
  version: 2023.5.0
  cloudProfiles:
  - name: eu-de-1
    image: coreos-2023.5.0
```
