### ISSUE TITLE
Implement `ControlPlane` controller for OpenStack provider

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extension-provider-openstack#12]
Similar to how we have implemented the `ControlPlane` extension resource controller for the [AWS provider](https://github.com/gardener/gardener-extensions/tree/master/controllers/provider-aws/pkg/controller/controlplane) let's please now do it for OpenStack.

Based on [the current implementation](https://github.com/gardener/gardener/blob/master/example/90-shoot-openstack.yaml) the `ControlPlaneConfig` should look like this:

```yaml
apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
kind: ControlPlaneConfig
cloudControllerManager:
  featureGates:
    CustomResourceValidation: true
loadBalancerProvider: haproxy
```

No `ControlPlaneStatus` needs to be implemented right now (not needed yet).
