### ISSUE TITLE
Implement `Infrastructure` controller for OpenStack provider

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extension-provider-openstack#13]
Similar to how we have implemented the `Infrastructure` extension resource controller for the [AWS provider](https://github.com/gardener/gardener-extensions/tree/master/controllers/provider-aws/pkg/infrastructure) let's please now do it for GCP.

Based on [the current implementation](https://github.com/gardener/gardener/blob/master/example/90-shoot-openstack.yaml#L13-L19) the `InfrastructureConfig` should look like this:

```yaml
apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
kind: InfrastructureConfig
networks:
# router:
#   id: uuid
  floatingPoolName: fip-network-one
  zones:
  - name: eu-1a
    workers: 10.250.0.0/19
```

Based on the [current implementation](https://github.com/gardener/gardener/blob/master/charts/seed-terraformer/charts/openstack-infra/templates/_main.tf#L102-L128) the `InfrastructureStatus` should look like this:

```yaml
---
apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
kind: InfrastructureStatus
networks:
  router:
    id: uuid
  cluster:
    id: uuid
  floatingPool:
    id: uuid
  subnets:
  - purpose: nodes
    id: uuid
securityGroups:
- purpose: nodes
  id: uuid
  name: sec-group-name
```

The current infrastructure creation/deletion implementation can be found [here](https://github.com/gardener/gardener/blob/master/pkg/operation/cloudbotanist/openstackbotanist/infrastructure.go). Please try to change as little as possible (with every change the risk that we break something increases!) and just move the code over into the extensions infrastructure actuator.
