### ISSUE TITLE
Categorize non-existing `floatingPoolName` as configuration issue with a better error message

### ISSUE THREAD

**Issue by stoyanr** [gardener/gardener-extension-provider-openstack#328]
**How to categorize this issue?**

/area ops-productivity
/kind enhancement
/priority 3
/platform openstack

**What would you like to be added**:
Currently, if `spec.provider.infrastructureConfig.floatingPoolName` refers to a non-existing floating pool, the reconciliation fails with the following error:

```yaml
lastError:
  codes:
  - ERR_CONFIGURATION_PROBLEM
  - ERR_INFRA_UNAUTHORIZED
  description: |-
    Error reconciling infrastructure: failed to apply the terraform config: Terraform execution for command 'apply' could not be completed:

    * Your query returned no results. Please change your search criteria and try again.
      on tf/main.tf line 19, in data "openstack_networking_network_v2" "fip":
      19: data "openstack_networking_network_v2" "fip" {
```

Although this error captures the Terraform error correctly and is categorized as `ERR_CONFIGURATION_PROBLEM`, there are at least 2 issues with it:

* It is also categorized as `ERR_INFRA_UNAUTHORIZED` which is incorrect. This is because the string `Your query returned no results` that is used to categorize it is ambiguous and used in regexes for both error types.
* The error message is verbose but does not clearly point to the actual issue.

Instead of relying on regexes to categorize this error, the issue could be checked for and reported by a `ConfigValidator` implementation, see https://github.com/gardener/gardener/pull/4547 and similar PRs for the GCP and AWS providers:
* https://github.com/gardener/gardener-extension-provider-gcp/pull/312
* https://github.com/gardener/gardener-extension-provider-aws/pull/395

**Why is this needed**:
