### ISSUE TITLE
Error code not added

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-openstack#605]
**How to categorize this issue?**

/area quality
/area ops-productivity
/kind bug
/platform openstack

**What happened**:
Infra is failing to be deleted with the following error:
```yaml
  status:
    lastError:
      description: 'Error checking infrastructure config: <nil>: Internal error: could
        not create Openstack client factory: Authentication failed'
      lastUpdateTime: "2023-04-05T06:59:15Z"
    lastOperation:
      description: 'Error checking infrastructure config: <nil>: Internal error: could
        not create Openstack client factory: Authentication failed'
      lastUpdateTime: "2023-04-05T06:59:15Z"
      progress: 50
      state: Error
      type: Reconcile
```

This error message should have been categotized as `ERR_INFRA_UNAUTHENTICATED` as it contains the string `Authentication failed` which should be matched in https://github.com/gardener/gardener-extension-provider-openstack/blob/9d13b55441fa56a698aff3712ba71f097ad29778/pkg/apis/openstack/helper/error_codes.go#L24

**What you expected to happen**:
The Infrastructure lastError to have the error code `ERR_INFRA_UNAUTHENTICATED` added.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:

**Environment**:

- Gardener version (if relevant):
- Extension version: v1.32.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:
