### ISSUE TITLE
Add domain field to `openstackv1alpha1.FloatingPool`

### ISSUE THREAD

**Issue by rfranzke** [gardener/gardener-extension-provider-openstack#73]
**What would you like to be added**:
Let's add a new optional `domain *string` field to the [`openstackv1alpha1.FloatingPool`](https://github.com/gardener/gardener-extension-provider-openstack/blob/master/pkg/apis/openstack/v1alpha1/types_cloudprofile.go#L63-L72). It allows to configure that the given floating pool is only available in the specified domain. If no domain is specified then it is valid in all domains:

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: CloudProfile
metadata:
  name: openstack
spec:
  type: openstack
  ...
  providerConfig:
    apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
    kind: CloudProfileConfig
    ...
    constraints:
      floatingPools:
      - name: fp-pool-1 #valid in `domain1` domain in `eu-1` region
        region: eu-1
        domain: domain1
      - name: fp-pool-2 # valid in all domains in `eu-1` region
        region: eu-1
      - name: fp-pool-3 # valid in all domains and all regions
      loadBalancerProviders:
      - name: haproxy
```

**Why is this needed**:
In some OpenStack environments the floating pools differ based on region (already supported) **and domain** (not yet supported). Reflecting this in the `CloudProfile` will make the user experience better and allows the Gardener Dashboard to provide the correct values in the cluster creation dialog.
