### ISSUE TITLE
If shoot creation fails on `ensureNetwork`, then cluster cannot be deleted

### ISSUE THREAD

**Issue by RadaBDimitrova** [gardener/gardener-extension-provider-openstack#890]
**How to categorize this issue?**

/area networking
/kind bug
/platform openstack

**What happened**:

On shoot creation when we reach "ensure network" here:
https://github.com/gardener/gardener-extension-provider-openstack/blob/c14529a1d7c69e071a077ae1c88d67a24a75eab9/pkg/controller/infrastructure/infraflow/reconcile.go#L58-L62

The reconciliation flow graph can be severed in case of a failure in the flow task, for example here:
https://github.com/gardener/gardener-extension-provider-openstack/blob/c14529a1d7c69e071a077ae1c88d67a24a75eab9/pkg/controller/infrastructure/infraflow/reconcile.go#L240-L246

After execution of the task the following state was observed, so the network wasn't set:
```
state:
    apiVersion: openstack.provider.extensions.gardener.cloud/v1alpha1
    data:
      FloatingNetwork: ...
      FloatingNetworkName: ...
    kind: InfrastructureState
```
Shoot gets stuck in creation state and after triggering shoot deletion the following snippet fails the "recover subnet ID" task with "network not found":
https://github.com/gardener/gardener-extension-provider-openstack/blob/c14529a1d7c69e071a077ae1c88d67a24a75eab9/pkg/controller/infrastructure/infraflow/reconcile.go#L311-L318

**What you expected to happen**:
Shoot deletion to succeed after reconciliation failed.

**How to reproduce it (as minimally and precisely as possible)**:
N/A
