### ISSUE TITLE
Shoots in existing networks

### ISSUE THREAD

**Issue by dkistner** [gardener/gardener-extension-provider-openstack#99]
**How to categorize this issue?**
/kind enhancement
/priority normal
/platform openstack

**What would you like to be added**:
Like for other cloud providers we want to enable OpenStack Shoot deployments into existing networks. As we do it on the other infrastructures we will manage subnet as smallest unit in the network and it need to be disjunct from the other subnets in the network.

A example configuration could look like this.
```yaml
kind: InfrastructureConfig
networks:
  id: <id-of-my-network>
  workers: <cidr-of-subnet-in-my-network>
```
